grep:
  cmd: ./grep-wrap.py $1

re:
  cmd: ./re-wrap.py $1

pcre2:
  cmd: ./pcre2-wrap.py $1

rsaregex:
    cmd: ./rsaregex-wrap.py $1

js:
  cmd: ./js-wrap.py $1

java:
  cmd: ./java-wrap.py $1

net:
  cmd: ./net-wrap.py $1

